### ISSUE TITLE
editor can't open

### ISSUE THREAD

**Issue by gameplay134** [zenkovich/o2#36]
![error o2 engine](https://user-images.githubusercontent.com/80104725/123020917-4a336180-d3fd-11eb-8b4b-1e34c8dc54c7.PNG)

**Comment by anzenkovich** [comment]
try set debug working directory to $(TargetDir). By default Visual Studio runs binary from solution directory, but exe should run from root repo folder
![image](https://user-images.githubusercontent.com/43806582/123035751-8910e980-d3f4-11eb-86b0-14c1a40e50b3.png)

**Comment by gameplay134** [comment]
debug failed
![o2 editor debugging](https://user-images.githubusercontent.com/80104725/123042731-7234bc00-d421-11eb-88e6-4920a537a11a.PNG)

**Comment by anzenkovich** [comment]
You need to set a slightly different value for Working directory: $(Target**Dir**). And set Editor app as startup project, by clicking right button on this project in VS
