### ISSUE TITLE
Fails to Compile

### ISSUE THREAD

**Issue by opiter09** [zenkovich/o2#37]
![Screenshot (388)](https://user-images.githubusercontent.com/92452568/156898356-83e81241-06e8-491a-80a4-167c84ef88dd.png)
Literally only one error keeping this from working. The file it refers to definitely exists, so I don't get what's going on.

**Comment by anzenkovich** [comment]
Looks like you downloaded only engine, that is just a library. Try load the [Pet Story](https://github.com/zenkovich/PetStory) - demo project. Don't forget about submodules :) You can open solution Platforms/Windows/PetStory.sln. It should have several projects inside. Select EditorApp or App as startup project (in context menu) to run editor or game applications. Then just compile and run. Or just run .exe from Bin/Win directory. If you have any problems, you can write me in my chat - https://discord.gg/FqBBYpYGfS
![image](https://user-images.githubusercontent.com/43806582/156912070-083a020a-c760-489c-a1d2-02fdc4e054f0.png)
